### ISSUE TITLE
Issues with port 8088

### ISSUE THREAD

**Issue by anarwal27** [influxdata/influxdata-docker#115]
I am using influxdb-docker image (docker pull influxdb), it starts fine but when I try to get in container (docker exec -it CONTAINER_ID bash) and use `influxd`, I get an error
`run: open server: listen: listen tcp 127.0.0.1:8088: bind: address already in use`
I verified there is nothing running on this port, additionally I also tried to use different port in influxdb.conf, `bind-address = ":18088"` however it still doesn't work giving me `run: open server: listen: listen tcp 127.0.0.1:18088: bind: address already in use`, what am I doing wrong in here?

**Comment by jsternberg** [comment]
How did you start the original container? `docker exec` can only be used on a running container. That makes me think you have `influxd` already running in the container and then you tried to run it again in the same container.

**Comment by anarwal27** [comment]
Got it, I had the same doubt, but then how do I access CLI in the container? Is HTTP API call the only way then?

**Comment by jsternberg** [comment]
I'm not sure what commands you want to run. Can you give me any details on what you're trying to do? Using `docker exec` is fine, you just can't run `influxd` twice in the same container.

**Comment by anarwal27** [comment]
After logging in container I want to run `SHOW DATABASES`, `CREATE DATABASE` and basic influxdb commands meant for Influxdb cli.  I can `docker exec` and enter container, like earlier I was able to run cli when I entered container

**Comment by jsternberg** [comment]
The program you're looking for is `influx`. `influxd` is the server and wouldn't allow you to run queries anyway. Be aware there is an issue with using `docker exec` and `influx` as documented in the `CLI / SHELL` section of the README.

I'm going to close this issue since it does not appear to be a bug in the image. If you're still having issues, repost this issue to our [community](https://community.influxdata.com/) website and give me a ping to the link here.
