### ISSUE TITLE
Docker has no lm_sensors/lm-sensors

### ISSUE THREAD

**Issue by sureguy** [influxdata/influxdata-docker#186]
Neither the debian nor the alpine dockers have lm-sensors (lm_sensors in alpine) which is required for [[inputs.sensors]] to work.

It would be great if these were added to the docker images by default.

**Comment by ccmpbll** [comment]
I second this. I would like a way to get the package installed without having to fork your repo and edit the dockerfile with the packages I want installed. 

I wonder if a good solution to this problem is creating an environment variable that will allow us to specify the extra packages we want installed when the container is created? I will work on this some to see if I can get it to work.

**Comment by powersj** [comment]
Hi,

Does look like lm-sensors is included! closing this one out.
