### ISSUE TITLE
Problem with bind-address not being replaced  by data provided in /etc/influxdb/influxdb.conf

### ISSUE THREAD

**Issue by pragmaticivan** [influxdata/influxdata-docker#195]
/etc/influxdb/influxdb.conf content:
```
bind-address = ":8088"

[meta]
  dir = "/var/lib/influxdb/meta"

[data]
  dir = "/var/lib/influxdb/data"
  engine = "tsm1"
  wal-dir = "/var/lib/influxdb/wal"
```

influxd config result:
```
bash-4.3# influxd config

Merging with configuration at: /etc/influxdb/influxdb.conf
reporting-disabled = false
bind-address = "127.0.0.1:8088"
```

BTW, I tested replacing values inside a context, like `[meta]` and it works. It just don't work with the global values.

**Comment by jsternberg** [comment]
It's a confusing legacy part of the system. The global bind address is for some weird port that's used only by backup I think (and maybe restore, but I'm not sure about that). You're likely looking for the bind address in the http section:

```
[http]
  enabled = true
  bind-address = ":8086"
```

So if you want to change the one used for http, you can set `INFLUXDB_HTTP_BIND_ADDRESS`.

The global biind address used to be used for clustering, but that was removed before we hit 1.0 and the config option never left since it was still used and the global configuration option is used in our enterprise product.

I hope that helps. If I'm misunderstanding the issue, please tell me and I'll reopen the issue.

**Comment by pragmaticivan** [comment]
I'm actually looking for the backup part of it.
