### ISSUE TITLE
create a basic database through the environment

### ISSUE THREAD

**Issue by vyscond** [influxdata/influxdata-docker#20]
Hi guys! Can we have a default step on the Dockerfile to create one (or many) database(s) while building new images?

Thanks :)

**Comment by jsternberg** [comment]
@vyscond I don't think we are going to be adding this to the image. We would need to add this to the entrypoint script and we prefer for the image to be as bare as possible so others could build on it without having extra stuff if they don't need it.

If you have a specific method you have in mind, feel free to submit a PR, but my initial guess is that it would be unlikely I would accept it since these extras are pretty easy for a person to add themselves if they need it and Docker Hub is a free service where you can have your image automatically built.
