### ISSUE TITLE
Kapacitor all example in doc should include the volume from host /var/lib/kapacitor

### ISSUE THREAD

**Issue by rolele** [influxdata/influxdata-docker#27]
I open this issue because it was not clear to me how the kapacitord was able to restart with existing tick alert setup in the past.
this is the issue:
https://github.com/influxdata/kapacitor/issues/985

the answer is very clear, kapacitor is saving the data about its state in /var/lib/kapacitor so if you share this volume with the host, if you restart you get back your previously registered tasks.

Many examples on the doc does not include this volume sharing so it make it a little bit unclear.

**Comment by jsternberg** [comment]
I'm not exactly sure what you mean. The volume management is part of docker and I don't think we want to explain how docker volumes work in our documentation since you can just look at docker's documentation, which will be more up to date and more accurate. We do have this at the beginning:

```
You can also have Docker control the volume mountpoint by using a named volume.

$ docker run -p 9092:9092 \
      -v kapacitor:/var/lib/kapacitor \
      kapacitor
```

What would you like to see to make it more obvious that `/var/lib/kapacitor` is the persistent storage mountpoint?

**Comment by rolele** [comment]
nevermind. you are probably right
