### ISSUE TITLE
Authentication Failing

### ISSUE THREAD

**Issue by dantespe** [influxdata/influxdata-docker#3]
InfluxDB Image Version: 0.13
Docker Version: 1.11.2

I think there is an issue with how InfluxDB is handling authentication.

Steps to set up Authentication:
1. `docker run -d --name=influxdb -v /home/../influxdb.conf:/etc/sysconfig/influxdb.conf -p 8083:8083 -p 8086:8086 influxdb `
2. `docker exec -it influxdb /bin/bash`
3. `influxd -config /etc/sysconfig/influxdb.conf`
4. `influx`
5. `create user <user> with password '<password>' with all privileges`
6. Leave InfluxDB console and restart docker container

From a different machine, I was able to connect to the host and `drop user <user>` without having credentials.

**Comment by gunnaraasen** [comment]
Changes made in `docker exec` need to be committed otherwise they are not persisted on `docker restart` so I suspect the config file enabling auth is not being used. The [InfluxDB Docker docs](https://hub.docker.com/_/influxdb/) show the correct way to pass in a configuration file to an InfluxDB Docker container.

```
docker run -p 8083:8083 -p 8086:8086 \
      -v $PWD/influxdb.conf:/etc/influxdb/influxdb.conf:ro \
      influxdb -config /etc/influxdb/influxdb.conf
```
