### ISSUE TITLE
RPC for backup/restore not exposed in container

### ISSUE THREAD

**Issue by kmmanto** [influxdata/influxdata-docker#303]
I'm trying to open up the port for backup/restore in InfluxDB but when I run:

influxd backup -portable -host [IP]:8088 /backup

I get this error message:
2019/01/24 11:08:55 Download shard 0 failed copy backup to file: err=read tcp [IP]:45160->[IP]:8088: read: connection reset by peer, n=0.  Waiting 2s and retrying (3)..

docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                                    NAMES
9fea00321e4c        influxdb            "/entrypoint.sh in..."   40 minutes ago      Up 40 minutes       0.0.0.0:8083->8083/tcp, 0.0.0.0:8086->8086/tcp, **0.0.0.0:8088->8088**/tcp   influxdb1

**Comment by angelfs** [comment]
I have the same problem, any solution?

**Comment by jsternberg** [comment]
I would likely not advise doing this since exposing the backup/restore functionality to an open internet probably isn't what you want, but the reason why it doesn't work is because the backup/restore port is set to listen only on localhost so even if you forward the port with docker you still won't be able to connect to it. You can override this by setting the bind address to `0.0.0.0:8088` inside of the configuration file or the appropriate environment variable.

It might be better to use `docker exec` to get a shell in the actual container. Then you don't need to expose any port because it would be as if you were on the same host as the influxd process.

I hope that helps. I'm going to close this because no changes to the image are going to be made regarding this.

**Comment by code-mechine** [comment]
> I have the same problem, any solution?

sudo docker run -it --name influx -d \
                    --restart=always \
                    -p 8086:8086 \
                    -p 8088:8088 \
                    -v /home/uaq/itom/influx/influx_1/conf:/etc/influxdb \
                    -v /data/influxdb_1:/var/lib/influxdb \
                    -e INFLUXDB_BIND_ADDRESS=":8088" \
                    influxdb
