### ISSUE TITLE
Base image of Telegraf shows vulnerabilities on Docker Hub

### ISSUE THREAD

**Issue by GaryRogers** [influxdata/influxdata-docker#305]
Any plans to rev the base image of the Telegraf Docker image? 

Docker Hub is showing vulnerabilities, probably related to the base image, not anything in Telegraf. 

See [Docker Hub Scans Page](https://hub.docker.com/_/telegraf/scans/library/telegraf/1.9.2)

**Comment by russorat** [comment]
@GaryRogers that link is a 404. is this still an issue?

**Comment by russorat** [comment]
nvm had to log in. thanks we will look into it.  @jsternberg fyi

**Comment by danielnelson** [comment]
I feel like the docker hub scan page is not accurate enough to be taken very seriously.  I looked at the `/usr/lib/x86_64-linux-gnu/libkrb5.so.3.3` file with a supposed critical vulnerability, and found that its package [libkrb5-3](https://packages.debian.org/stretch/libkrb5-3) is the latest version in stretch.  Considering that the vulnerability listed is 2 years old, the fix was probably backported by Debian.

**Comment by GaryRogers** [comment]
I can see that. Wouldn't surprise me if Docker Hub's scanner doesn't consider back-ported fixes in distros. Thanks for giving it a look.
