### ISSUE TITLE
entrypoint.sh

### ISSUE THREAD

**Issue by mohsin106** [influxdata/influxdata-docker#323]
hi, i don't have an issue but i'm just trying to understand what entrypoint.sh is doing. if someone can explain that would be greatly appreciated. thank you!

**Comment by danielnelson** [comment]
@mohsin106 I'll try to help if you can link to the entrypoint.sh you are looking at.

**Comment by mohsin106** [comment]
here are the links:
[Telegraf](https://github.com/influxdata/influxdata-docker/blob/master/telegraf/1.11/entrypoint.sh)
[Kapacitor](https://github.com/influxdata/influxdata-docker/blob/master/kapacitor/1.5/entrypoint.sh)
[InfluxDB](https://github.com/influxdata/influxdata-docker/blob/master/influxdb/1.7/entrypoint.sh)

thank you

**Comment by jsternberg** [comment]
The `/entrypoint.sh` file is used as a custom thing to `exec` when entering the container. Inside of docker, there's the `entrypoint` and the `cmd`. When you start a container with no arguments, docker will default to using the `entrypoint + cmd` as the command that executes within the container. If you use arguments, then the `cmd` is overwritten with whatever you specify. It is also possible to override the `entrypoint` with `--entrypoint`.

The reason we use `/entrypoint.sh` is because, as advised in the [review guidelines](https://github.com/docker-library/official-images/blob/master/README.md#consistency) for an official image, we want `bash -l` to work if used on the image, we want any command line arguments with dashes to be to the related binary, and we want it to run the default configuration if no arguments are specified. The `/entrypoint.sh` looks at the arguments and determines how to exec to get the correct behavior. This is why the following is possible:

```bash
# will run the influxd binary with the -config argument
docker run influxdb -config /myconfig.toml
# will run bash inside of the image without running the database
docker run -it influxdb bash -l
# will run influxdb
docker run influxdb
```

For the `influxdb` image itself, the entrypoint also has additional code to allow for initializing a database with environment variables. This is used by people who want to run influxdb as a sidecar in their development or CI environments and don't want to deal with writing their own initialization code for a simple test database. I would not recommend using those options if running these images in production, but if it works, it works.

I hope that helps.
