### ISSUE TITLE
All InfluxDB have engine set instead of index-version

### ISSUE THREAD

**Issue by Esity** [influxdata/influxdata-docker#345]
all the influxdb images have ```engine = tsm1``` set. They should be using ```index-version = tsi1```

Will open a PR to fix this. Also this means that all docker containers default to using inmem since the index-version config item isn't set.

**Comment by jsternberg** [comment]
`engine` is a different option than `tsm1` and should be set. It doesn't really matter since there's one option, but it is fine for it to be set.

I am not sure we can reasonably change the `index-version` to `tsi1` in the image by default. This change would essentially change the underlying implementation under people who are using the images. The docker image is meant to use whatever the default is so if `inmem` is the default, that's what the docker image should use.

It is pretty easy to use an environment variable to modify the default index version or to create a custom image that overwrites the default configuration file.

**Comment by jsternberg** [comment]
Since `index-version` is `inmem` by default for 1.x, I'm going to close this because the docker image is supposed to use the same default values as the software itself.

If you want to use `tsi1` it is easy to configure that using an environment variable.
