### ISSUE TITLE
Expose port 8083 for influxdb 1.1.1

### ISSUE THREAD

**Issue by zshamrock** [influxdata/influxdata-docker#48]
Port 8083 administrator web interface is only expose in the Alpine image. 

Is there a reason why this port is not exposed for non-alpine version?

**Comment by jsternberg** [comment]
That's actually a mistake. It's not supposed to be exposed in either. I must have made that mistake really early when I was first developing the images since I was originally going to expose the port and then didn't because expose wouldn't have worked.

The web administrator interface was also deprecated in 1.1 and there was a mistake in the 1.1.0 image where we didn't disable it as part of the default configuration file.

The reason it wasn't exposed originally was because expose chooses a random port and choosing a random port for the web interface isn't really useful since it still needs to contact the 8086 port to do anything. I also didn't want to expose the web admin interface by default.

I'll remove it from alpine so it's consistent. If you still want to expose it before it's been removed, you can just do `-p 8083:8083`. Expose only controls what gets forwarded when you do `-P`.

**Comment by zshamrock** [comment]
Ok, clear. So, it is planned to be removed? 

Actually, this took me a while trying to understand why http://localhost:8083 didn't work anymore after upgrade to 1.1 even if I have exposed the port explicilty by `-p 8083:8083`, until I've checked the config file where it was disabled by default:
```
[admin]
  enabled = false
```

So the admin web interface goes out completely or you will keep only HTTP API port? Or there will the replacement for it?

**Comment by jsternberg** [comment]
We are planning to remove it from the project itself, but there's no current plan to replace it. It was too difficult for us to maintain and it was more just a hacky thing that was added at some point in an earlier release. But, it would be really easy to just take the source code and make it into an unofficial separate project.

If you want to run it temporarily in the meantime, you can still enable it by setting `INFLUXDB_ADMIN_ENABLED=true` as an environment variable.

**Comment by jsternberg** [comment]
Fixed via #49.
