### ISSUE TITLE
Version 2.0.6 image says version 2.0.5 at the Login Screen

### ISSUE THREAD

**Issue by p-schneider** [influxdata/influxdata-docker#484]
When running the 2.0.6 docker image I would expect the Login Page to also display that version.

Step to reproduce:
Run a fresh container like this
```
docker run \
-e DOCKER_INFLUXDB_INIT_USERNAME=admin \
-e DOCKER_INFLUXDB_INIT_PASSWORD=password \
-e DOCKER_INFLUXDB_INIT_ORG=example \
-e DOCKER_INFLUXDB_INIT_BUCKET=bucket \
-e DOCKER_INFLUXDB_INIT_MODE=setup \
--rm -ti -p 8086:8086 influxdb:2.0.6
```

expected Result: Version 2.0.6 displayed at the bottom of the Login screen

actual Result: It says `Version 2.0.5 ('7c3ead)` at the Login screen
![image](https://user-images.githubusercontent.com/2636101/116726442-91940780-a9e3-11eb-8511-a12fbeeec9f2.png)

In the startup of that container I see 
`{"log_id": "0TpvnvP0000", "version": "2.0.6", "commit": "4db98b4c9a", "build_date": "2021-04-29T16:48:12Z"}` so it is correctly starting version 2.0.6.

Also: That `'7c3ead` looks like some substring/sed magic failed to grab the first 7 hex characters of a commit but picked the `'` and 6 hex characters instead.

**Comment by danxmoran** [comment]
There are a couple things going wrong here.

The mismatched version string is a known issue (influxdata/influxdb#20007). We've been working around it by bumping the UI constant before every release, but we missed it in our rush to get the 2.0.6 hotfix out the door.

The mismatched commit hash is new. It's happening because we've switched to a system of pulling UI assets from a repo shared w/ InfluxDB Cloud ([influxdata/ui](https://github.com/influxdata/ui/)), and the build process for the UI assets is injecting the commit hash for that repo into the page. https://github.com/influxdata/ui/commit/7c3ead341c9e40020812939672758ad8777731da is the UI commit tagged for the 2.0.5 release (reused in the 2.0.6 hotfix), and the hashes line up.

@wbaker85 do you want me to transfer this issue to the UI repo? Or would you rather create a separate issue there?

**Comment by wbaker85** [comment]
I think the existing [ui#334](https://github.com/influxdata/ui/issues/334) covers the fix for the problem, which is that we need the frontend to get the info from the backend.

I'll make a separate issue in the UI repo to make sure the version & hash is updated one way or another prior to the next release so that we can track it.

**Comment by wbaker85** [comment]
Closed by [influxdb#21564](https://github.com/influxdata/influxdb/pull/21564)

**Comment by jerry1333** [comment]
I'm having similar issue with 2.0.8 version showing 2.0.7 in UI but 'influxd version' shows "InfluxDB 2.0.8 (git: e91d41810f) build_date: 2021-08-13T18:22:30Z"
BUT
i did full restore ('influx restore --full') from backup taken on 2.0.7 server

**Comment by wbaker85** [comment]
We've had cases where the browser's cache of localstorage would prevent fetching the version number properly - should be fixed in the next release (see https://github.com/influxdata/influxdb/issues/22210).

If you log out and then log back in, does the version number display correctly?

**Comment by jerry1333** [comment]
Oh yes, now its showing it correctly (had to clear cache).
Thanks!
