### ISSUE TITLE
docker init port should be updated to 8086

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdata-docker#497]
Noticed when using the `DOCKER_INFLUXDB_INIT_MODE` variables, that the port is still 9999. 

https://github.com/influxdata/influxdata-docker/blob/e5b413dcc8fa77422f4a357c02c60a75326d61a7/influxdb/2.0/Dockerfile#L61

https://github.com/influxdata/influxdata-docker/blob/e5b413dcc8fa77422f4a357c02c60a75326d61a7/influxdb/2.0/alpine/Dockerfile#L72

**Comment by danxmoran** [comment]
@russorat this is intentional. The reasoning is/was: auto-setup has to boot a server to run `influx setup` and other user-defined scripts. If we booted the server on the final user-requested port that gets exposed outside of the container (default 8086) then automation like k8s healthchecks might report the server as booted up & ready before all the auto-setup logic completes. To avoid race conditions, we:
1. Boot the server on `INFLUXD_INIT_PORT` (default 9999)
2. Run all the auto-setup logic against it at that port
3. Shut down the server
4. Boot the server back up, using 8086/the user-requested port

**Comment by russorat** [comment]
ah thanks for the explanation! closing.
