### ISSUE TITLE
docker.io/library/chronograf is not up-to-date with release versions offered on website

### ISSUE THREAD

**Issue by linearregression** [influxdata/influxdata-docker#54]
Per https://www.influxdata.com/downloads/
Tehre shold be higher versions for chronograf.
docker.io/library/chronograf

**Comment by jsternberg** [comment]
Sorry for not having an image. The issue has been that chronograf has been undergoing a major change and I wasn't aware that it was in a state where it could be turned into an image. I'll create the images for these, but be aware that the versions will be semi-meaningless until chronograf goes out of beta. The reason is mostly because we try to keep the version numbers lined up so while there is a 1.1.0-beta6 on the website, there may never be a 1.1.0 if chronograf is taken out of beta after 1.2 is released.

I should be able to create images for the specific versions though and I can tag latest as whatever is currently the most recent beta.

**Comment by jsternberg** [comment]
Chronograf 1.3 has been officially released and the image is now updated.
